// src/pages/Settings/settingsStyles.js
const styles = {
  container: {
    maxWidth: "900px",
    margin: "2rem auto",
    padding: "2rem",
    backgroundColor: "#ffffff",
    borderRadius: "10px",
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    marginLeft: "70px",
  },
  heading: { fontSize: "32px", fontWeight: "700", marginBottom: "8px", color: "#111827" },
  subheading: { fontSize: "16px", color: "#6b7280", marginBottom: "30px" },
  cardList: { display: "flex", flexDirection: "column", gap: "16px" },
  card: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "#f9fafb",
    padding: "16px 20px",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "background-color 0.2s",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  cardIcon: { color: "#3f51b5", marginRight: "16px", flexShrink: 0 },
  cardContent: { flexGrow: 1 },
  cardTitle: { fontSize: "18px", fontWeight: "600", marginBottom: "4px", color: "#111827" },
  cardDescription: { fontSize: "14px", color: "#6b7280" },
  arrow: { fontSize: "24px", color: "#6b7280", flexShrink: 0 },

  backBtn: {
    marginBottom: 20,
    background: "none",
    border: "none",
    color: "#3f51b5",
    fontSize: 16,
    cursor: "pointer",
    fontWeight: "600",
    padding: 0,
  },

  // Delete
  deleteButton: {
    backgroundColor: "#e74c3c",
    color: "#fff",
    border: "none",
    padding: "12px 24px",
    fontSize: "16px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "bold",
    boxShadow: "0 2px 6px rgba(231, 76, 60, 0.5)",
    transition: "background-color 0.3s",
  },

  // About
  aboutContainer: { lineHeight: 1.6, color: "#111827" },
  aboutHeader: {
    backgroundColor: "#596bd1ff",
    padding: "25px 30px",
    borderRadius: "12px",
    color: "#ffffff",
    marginBottom: "30px",
  },
  aboutTitle: { fontSize: "28px", fontWeight: "700", marginBottom: "10px" },
  aboutSubtitle: { fontSize: "18px", color: "#ffffff", fontWeight: "500", maxWidth: "600px" },
  section: { marginBottom: "36px" },
  sectionTitle: { fontSize: "22px", fontWeight: "700", marginBottom: "14px", color: "#111827" },
  text: { fontSize: "17px", color: "#4b5563", maxWidth: "720px", lineHeight: 1.7 },
  featureGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "20px",
  },
  featureCard: {
    display: "flex",
    alignItems: "flex-start",
    gap: "15px",
    backgroundColor: "#f9fafb",
    borderRadius: "12px",
    padding: "18px 20px",
    border: "1px solid #e5e7eb",
    boxShadow: "0 1px 4px rgba(0,0,0,0.05)",
  },
  featureIcon: { fontSize: "22px", color: "#3f51b5", marginTop: 4 },
  featureTitle: { fontWeight: "600", fontSize: "16.5px", marginBottom: "4px", color: "#111827" },
  featureDesc: { fontSize: "15px", color: "#4b5563" },
  devCardContainer: { display: "flex", gap: "20px", flexWrap: "wrap" },
  devCard: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    backgroundColor: "#f9fafb",
    padding: "14px 18px",
    borderRadius: "10px",
    border: "1px solid #e5e7eb",
    boxShadow: "0 1px 4px rgba(0,0,0,0.05)",
  },
  avatar: {
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    backgroundColor: "#3f51b5",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
    fontSize: "16px",
  },
  devName: { fontSize: "16px", fontWeight: "600", color: "#1f2937" },
  contactCard: {
    backgroundColor: "#f9fafb",
    padding: "16px 20px",
    borderRadius: "10px",
    border: "1px solid #e5e7eb",
    maxWidth: "500px",
  },
  contactRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "15.5px",
    color: "#374151",
    marginBottom: "12px",
  },
  contactIcon: { color: "#3f51b5" },
  emailLink: { color: "#3f51b5", textDecoration: "underline" },

  // Account: profile pic
  profilePicContainer: {
    width: 80,
    height: 80,
    borderRadius: "50%",
    overflow: "hidden",
    border: "2px solid #3f51b5",
    backgroundColor: "#e5e7eb",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  profilePic: { width: "100%", height: "100%", objectFit: "cover" },
  profilePicPlaceholder: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#aaa",
  },
  uploadLabel: {
    backgroundColor: "#3f51b5",
    color: "#fff",
    padding: "10px 16px",
    borderRadius: "6px",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    fontSize: "14px",
    fontWeight: "600",
  },
  label: {
    display: "block",
    fontWeight: "600",
    color: "#374151",
    marginBottom: "10px",
  },
  input: {
    width: "100%",
    padding: "10px",
    marginBottom: "20px",
    borderRadius: "6px",
    border: "1px solid #ccc",
    fontSize: "15px",
    boxSizing: "border-box",
  },
  saveButton: {
    backgroundColor: "#3f51b5",
    color: "#fff",
    border: "none",
    padding: "10px 18px",
    fontSize: "15px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "600",
  },
  switch: { position: "relative", display: "inline-block", width: "46px", height: "24px" },
  slider: {
    position: "absolute",
    cursor: "pointer",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#ccc",
    transition: ".4s",
    borderRadius: "24px",
  },
};

export default styles;
