// src/pages/Settings/settingsStyles.js
const styles = {
  container: {
    fontFamily: "'Inter', 'Segoe UI', Arial, sans-serif",
    marginLeft: "50px",
    padding: "40px 60px",
    minHeight: "100vh",
  },
  
  // Hero Section (replaces heading/subheading)
  heroSection: {
    padding: "48px 40px",
    borderRadius: "16px",
    marginBottom: "48px",
    position: "relative",
    overflow: "hidden",
  },
  heroDecoration: {
    position: "absolute",
    top: "-50px",
    right: "-50px",
    width: "200px",
    height: "200px",
    background: "radial-gradient(circle, rgba(63, 81, 181, 0.15) 0%, transparent 70%)",
    borderRadius: "50%",
  },
  heroTitle: {
    fontSize: "2.5rem",
    fontWeight: "700",
    marginBottom: "12px",
  },
  heroSubtitle: {
    fontSize: "1.1rem",
    maxWidth: "600px",
  },

  heading: { fontSize: "32px", fontWeight: "700", marginBottom: "8px" },
  subheading: { fontSize: "16px", marginBottom: "30px" },
  
  // Card Grid (replaces cardList)
  cardList: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(350px, 1fr))",
    gap: "28px",
  },
  
  // Card Styling
  card: {
    padding: "32px",
    borderRadius: "16px",
    cursor: "pointer",
    transition: "all 0.3s ease",
    position: "relative",
    overflow: "hidden",
  },
  cardDecoration: {
    position: "absolute",
    top: 0,
    right: 0,
    width: "120px",
    height: "120px",
    background: "linear-gradient(135deg, #3f51b5 0%, #5a67d8 100%)",
    opacity: 0.08,
    borderRadius: "0 0 0 100%",
  },
  cardIconWrapper: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    marginBottom: "16px",
  },
  cardIcon: {
    padding: "14px",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.5rem",
    flexShrink: 0,
  },
  cardContent: { flexGrow: 1 },
  cardTitle: {
    fontSize: "1.5rem",
    fontWeight: "700",
    lineHeight: "1.3",
    margin: 0,
  },
  cardDescription: {
    fontSize: "1rem",
    lineHeight: "1.7",
    marginBottom: "16px",
  },
  arrow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontWeight: "600",
    fontSize: "0.95rem",
  },

  backBtn: {
    marginBottom: 20,
    background: "none",
    border: "none",
    fontSize: 16,
    cursor: "pointer",
    fontWeight: "600",
    padding: 0,
  },

  // Delete
  deleteButton: {
    backgroundColor: "#ef4444",
    color: "#fff",
    border: "none",
    padding: "14px 24px",
    fontSize: "1.05rem",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: "600",
    transition: "all 0.2s ease",
    boxShadow: "0 4px 12px rgba(239, 68, 68, 0.3)",
  },

  // About
  aboutContainer: { lineHeight: 1.6 },
  aboutHeader: {
    padding: "48px 40px",
    borderRadius: "16px",
    marginBottom: "48px",
    position: "relative",
    overflow: "hidden",
  },
  aboutTitle: { fontSize: "2.5rem", fontWeight: "700", marginBottom: "12px" },
  aboutSubtitle: { fontSize: "1.1rem", fontWeight: "500", maxWidth: "600px" },
  section: { marginBottom: "48px" },
  sectionTitle: { fontSize: "1.75rem", fontWeight: "600", marginBottom: "24px" },
  text: { fontSize: "1rem", maxWidth: "720px", lineHeight: 1.7 },
  featureGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "28px",
  },
  featureCard: {
    display: "flex",
    alignItems: "flex-start",
    gap: "16px",
    borderRadius: "16px",
    padding: "32px",
    transition: "all 0.3s ease",
    position: "relative",
    overflow: "hidden",
  },
  featureIcon: { fontSize: "1.5rem", marginTop: 4 },
  featureTitle: { fontWeight: "700", fontSize: "1.25rem", marginBottom: "8px" },
  featureDesc: { fontSize: "1rem", lineHeight: 1.7 },
  devCardContainer: { display: "flex", gap: "28px", flexWrap: "wrap" },
  devCard: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    padding: "24px",
    borderRadius: "16px",
    transition: "all 0.3s ease",
  },
  avatar: {
    width: "50px",
    height: "50px",
    borderRadius: "50%",
    backgroundColor: "#3f51b5",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
    fontSize: "1.25rem",
  },
  devName: { fontSize: "1.1rem", fontWeight: "600" },
  contactCard: {
    padding: "32px",
    borderRadius: "16px",
    maxWidth: "500px",
  },
  contactRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    fontSize: "1rem",
    marginBottom: "16px",
  },
  contactIcon: {},
  emailLink: { textDecoration: "underline" },

  // Account: profile pic
  profilePicContainer: {
    width: 100,
    height: 100,
    borderRadius: "50%",
    overflow: "hidden",
    border: "3px solid #3f51b5",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  profilePic: { width: "100%", height: "100%", objectFit: "cover" },
  profilePicPlaceholder: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  uploadLabel: {
    backgroundColor: "#3f51b5",
    color: "#fff",
    padding: "12px 24px",
    borderRadius: "10px",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    fontSize: "1rem",
    fontWeight: "600",
    transition: "all 0.2s ease",
    boxShadow: "0 4px 12px rgba(63, 81, 181, 0.3)",
  },
  label: {
    display: "block",
    fontWeight: "600",
    marginBottom: "8px",
    fontSize: "0.95rem",
  },
  input: {
    width: "100%",
    padding: "12px 16px",
    fontSize: "1rem",
    borderRadius: "8px",
    border: "2px solid",
    outline: "none",
    transition: "all 0.2s ease",
    boxSizing: "border-box",
    marginBottom: "24px",
  },
  saveButton: {
    backgroundColor: "#3f51b5",
    color: "#fff",
    border: "none",
    padding: "14px 24px",
    fontSize: "1.05rem",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: "600",
    transition: "all 0.2s ease",
    boxShadow: "0 4px 12px rgba(63, 81, 181, 0.3)",
  },
  switch: { position: "relative", display: "inline-block", width: "50px", height: "28px" },
  slider: {
    position: "absolute",
    cursor: "pointer",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#ccc",
    transition: ".4s",
    borderRadius: "28px",
  },
};

export default styles;